name: PR Opened

on:
  workflow_call:

env:
  NAME: "Alex"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          echo "this is build for ${{ github.repository }} "
          echo "My name is ${{ NAME }}"
          echo "My surname is ${{ secrets.SURNAME }}"
